# Generated by Django 5.2.1 on 2025-05-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonCatalogado',
            fields=[
                ('Name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Pokedex_Number', models.BigIntegerField(null=True)),
                ('Types', models.TextField(null=True)),
                ('Abilities', models.TextField(null=True)),
                ('Generation', models.TextField(null=True)),
            ],
        ),
    ]
