# Generated by Django 5.2.1 on 2025-06-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_pokemons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemoncatalogado',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='pokemoncatalogado',
            name='Abilities',
        ),
        migrations.RemoveField(
            model_name='pokemoncatalogado',
            name='Generation',
        ),
        migrations.RemoveField(
            model_name='pokemoncatalogado',
            name='Pokedex_Number',
        ),
        migrations.RemoveField(
            model_name='pokemoncatalogado',
            name='Types',
        ),
        migrations.AddField(
            model_name='pokemoncatalogado',
            name='abilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemoncatalogado',
            name='generation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemoncatalogado',
            name='pokedex_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemoncatalogado',
            name='types',
            field=models.TextField(blank=True, null=True),
        ),
    ]
